## DEFINE PARAMS STRUCTURE AND DEFAULT VALUES

## RUN GA (fitness function, params)
## INIT POP VARIABLE
## INIT OFFSPRING VARIABLE

### CALL SELECT FUNCTIONS FROM OTHER FILE TO CHOOSE PARENTS 
### CALL CROSSOVER FROM OTHER FILE (parent1, parent2)
### CALL MUTATE FROM OTHER FILE (crossover1, crossover2)
### PUSH (mutate1,mutate2) -> FINAL OFFSPRING RESULTS TO OFFSPRING VARIABLE
### CALL SURVIVOR SELECTION (population, offspring, params, evt families for crowding?) FROM OTHER FILE

## CALL IMPROVE INFEASIBLE SOLUTIONS FUNCTION AFTER A WHILE?

## LOG RESULTS

## ADJUST PARAMS DETERMINISTICALLY/DYNAMICALLY?
## RUN AGAIN FROM THE TOP UNTIL DONE

